### ISSUE TITLE
DossierTransfert.email needs validation : ActionMailer::MailDeliveryJob SMTP To address may not be blank: []

### ISSUE THREAD

**Issue by colinux** [betagouv/demarches-simplifiees.fr#7621]
```yml
job_data:
  job_class: ActionMailer::MailDeliveryJob
  job_id: f2b5e2fb-b776-4121-a569-b777168cfd21
  provider_job_id: 
  queue_name: mailers
  priority: 
  arguments:
  - DossierMailer
  - notify_transfer
  - deliver_now
  - args:
    - _aj_globalid: gid://tps/DossierTransfer/54818
    _aj_ruby2_keywords:
    - args
  executions: 0
  exception_executions: {}
  locale: en
  timezone: Paris
  enqueued_at: '2022-07-26T12:11:04Z'
```
